language: python
python:
- '3.7'
deploy:
  provider: pypi
  user: maxhumber
  password: $PYPI_PASSWORD
  on:
    tags: true

install:
  - "pip install pytest"
  - "pip install -e ."

script:
  - pytest tests/
